<a href="https://colab.research.google.com/github/Kavyacmd000/MAIN_PROJECT/blob/main/KAVYA_DA_FINAL_PROJECT_IKEA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Project Title

IKEA Global Product Catalog Analysis (2026)

# Domain
 Retail / E-commerce

# Objectives

- To analyze product price distribution across categories  
- To compare product prices across different countries  
- To identify the most common product categories  
- To study the relationship between product price and ratings  
- To evaluate the effect of discounts on pricing

# Outcome

- Identification of pricing patterns across categories and countries  
- Understanding of dominant product categories  
- Insights into relationship between price and ratings  
- Country-wise comparison of product pricing  
- Business recommendations for pricing and product strategy

# Dataset Information

## Source:

Kaggle:
https://www.kaggle.com/datasets/ranjithpanicker/ikea-global-product-catalog-and-price-2026

## Year / Timeline:

The dataset represents a IKEA’s product catalog as of February 2026. It does not contain time-based variables such as date or timestamp. Therefore, time-series analysis cannot be performed. The analysis will be cross-sectional, focusing on comparisons across countries, categories, and pricing.

## Dataset Description:

This dataset provides a cross-country snapshot of IKEA’s global product catalog across 46 international markets as of 27 February 2026.

It contains detailed product-level information including category hierarchy, pricing, ratings, and availability across different countries. The dataset enables comparative analysis of product assortment, pricing strategies, and market-level differences.

# Type of Analysis


1. Descriptive Analysis
Summarizes the dataset using statistical measures and distributions such as price, category counts, and ratings.

2. Diagnostic Analysis
Examines relationships between variables to understand patterns, such as price vs category and price vs ratings.

# Stages for DA Project

## Stage 1 – Problem Definition and Dataset Selection

## Problem Statement

This project aims to analyze IKEA’s global product catalog across multiple countries to understand pricing patterns, category distribution, and regional differences. The goal is to generate insights that can support business decisions such as pricing strategies and product positioning.

## Dataset Size

- Total Records: 401,046  
- Unique Products: 34,932  
- Number of Countries: 46  
- Number of Columns: 18  



## Column Description

- unique_id: Unique identifier combining product and country  
- product_id: Unique product identifier  
- product_name: Name of the product  
- product_type: Type of product  
- product_measurement: Product size or dimensions  
- product_description: Detailed description  
- main_category: Main product category  
- sub_category: Sub-category  
- product_rating: Average rating  
- rating_count: Number of ratings  
- badge: Product label or tag  
- online_selling: Availability online  
- url: Product link  
- price: Product price  
- currency: Currency type  
- discount: Discount information  
- sale_tag: Sale indicator  

- ## Country: Country of listing

Australia,Austria,Bahrain,Belgium,Canada,Chile,Colombia,Croatia,Czech Republic,Denmark,Egypt,Finland,France,Germany,Hungary,India,Ireland,Italy
Japan,Jordan,Kuwait,Malaysia,Mexico,Morocco,Netherlands,New Zealand,Norway,Oman,Philippines,Poland,Portugal,Qatar,Romania,Saudi Arabia,Serbia,Singapore,Slovakia,Slovenia,South Korea,Spain,Sweden,Switzerland,Thailand,UAE,UK,USA

# Initial EDA
- head,info,describe,shape,null check,duplicate check

In [ ]:
# import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
# Load dataset
df = pd.read_csv("IKEA-product-catalog.csv")
df.head()

,unique_id,product_id,product_name,product_type,product_measurements,product_description,main_category,sub_category,product_rating,product_rating_count,badge,online_sellable,url,price,currency,discount,sale_tag,country
0,10018194-Australia,10018194,ORDNING,Dish drainer,50x27x36 cm,"ORDNING Dish drainer, stainless steel, 50x27x3...",kitchenware-tableware,dishwashing-accessories,3.3,140.0,none,True,https://www.ikea.com/au/en/p/ordning-dish-drai...,30.00,AUD,none,NONE,Australia
1,10018194-Austria,10018194,ORDNING,Dish drainer,50x27x36 cm,An ORDNING stainless-steel dish drainer with t...,kitchenware-tableware,dishwashing-accessories,3.3,6.0,none,True,https://www.ikea.com/at/en/p/ordning-dish-drai...,27.99,EUR,none,NONE,Austria
2,10018194-Bahrain,10018194,ORDNING,Dish drainer,50x27x36 cm,"ORDNING Dish drainer, stainless steel, 50x27x3...",kitchenware-tableware,dishwashing-accessories,1.0,1.0,none,True,https://www.ikea.com/bh/en/p/ordning-dish-drai...,9.50,BHD,none,NONE,Bahrain
3,10018194-Belgium,10018194,ORDNING,Dish drainer,50x27x36 cm,An ORDNING stainless-steel dish drainer with t...,kitchenware-tableware,dishwashing-accessories,3.7,543.0,none,True,https://www.ikea.com/be/en/p/ordning-dish-drai...,29.99,EUR,none,NONE,Belgium
4,10018194-Canada,10018194,ORDNING,Dish drainer,"50x27x36 cm (19 5/8x10 5/8x14 1/8 "")","ORDNING Dish drainer, stainless steel, 19 5/8x...",kitchenware-tableware,dishwashing-accessories,3.7,543.0,none,True,https://www.ikea.com/ca/en/p/ordning-dish-drai...,34.99,CAD,none,NONE,Canada

In [ ]:
df.shape

(11011, 18)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11011 entries, 0 to 11010
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   unique_id             11011 non-null  object
 1   product_id            11011 non-null  int64
 2   product_name          11011 non-null  object
 3   product_type          11011 non-null  object
 4   product_measurements  11011 non-null  object
 5   product_description   11011 non-null  object
 6   main_category         11011 non-null  object
 7   sub_category          11011 non-null  object
 8   product_rating        11011 non-null  object
 9   product_rating_count  11011 non-null  object
 10  badge                 11011 non-null  object
 11  online_sellable       11011 non-null  bool
 12  url                   11011 non-null  object
 13  price                 11010 non-null  float64
 14  currency              11010 non-null  object
 15  discount              11010 non-null  object
 16  sale_tag              11010 non-null  object
 17  country               11010 non-null  object
dtypes: bool(1), float64(1), int64(1), object(15)
memory usage: 1.4+ MB

In [ ]:
df.describe()

         product_id         price
count  1.101100e+04  1.101000e+04
mean   1.019151e+07  7.128343e+03
std    1.330428e+06  5.754917e+04
min    1.004670e+05  2.500000e-01
25%    1.029236e+07  1.490000e+01
50%    1.039686e+07  6.497000e+01
75%    1.045319e+07  4.000000e+02
max    1.049414e+07  1.699990e+06

In [ ]:
df.shape

(11011, 18)

In [ ]:
## null checks
df.isnull().sum()

unique_id               0
product_id              0
product_name            0
product_type            0
product_measurements    0
product_description     0
main_category           0
sub_category            0
product_rating          0
product_rating_count    0
badge                   0
online_sellable         0
url                     0
price                   1
currency                1
discount                1
sale_tag                1
country                 1
dtype: int64

In [ ]:
df.duplicated().any()

np.False_

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.duplicated(subset=['unique_id']).sum()

np.int64(0)

## Stage 2 – Data Cleaning and Pre-processing

Handle missing values (impute or drop)

Handle duplicates

Treat outliers if required

Check skewness and apply transformations

Convert data types if needed

Feature transformations (date parts, derived fields if required for analysis)

In [ ]:
# Handling Missing Values
df.isnull().sum()

unique_id               0
product_id              0
product_name            0
product_type            0
product_measurements    0
product_description     0
main_category           0
sub_category            0
product_rating          0
product_rating_count    0
badge                   0
online_sellable         0
url                     0
price                   1
currency                1
discount                1
sale_tag                1
country                 1
dtype: int64

In [ ]:
df.dtypes

unique_id                object
product_id                int64
product_name             object
product_type             object
product_measurements     object
product_description      object
main_category            object
sub_category             object
product_rating           object
product_rating_count     object
badge                    object
online_sellable            bool
url                      object
price                   float64
currency                 object
discount                 object
sale_tag                 object
country                  object
dtype: object

**Numerical Column**

*   product_rating
*   product_rating_count
*   price
*   discount

In [ ]:
# Convert numeric columns
df['product_rating'] = pd.to_numeric(df['product_rating'], errors='coerce')
df['product_rating_count'] = pd.to_numeric(df['product_rating_count'], errors='coerce')
df['discount'] = pd.to_numeric(df['discount'].replace('none', np.nan), errors='coerce')

# Convert categorical columns
df['main_category'] = df['main_category'].astype('category')
df['sub_category'] = df['sub_category'].astype('category')
df['currency'] = df['currency'].astype('category')
df['country'] = df['country'].astype('category')

In [ ]:
df.dtypes

unique_id                 object
product_id                 int64
product_name              object
product_type              object
product_measurements      object
product_description       object
main_category           category
sub_category            category
product_rating           float64
product_rating_count     float64
badge                     object
online_sellable             bool
url                       object
price                    float64
currency                category
discount                 float64
sale_tag                  object
country                 category
dtype: object

In [ ]:
df['main_category']

0        kitchenware-tableware
1        kitchenware-tableware
2        kitchenware-tableware
3        kitchenware-tableware
4        kitchenware-tableware
                 ...
11006           outdoor-living
11007           outdoor-living
11008         outdoor-products
11009         home-improvement
11010          vrtni-proizvodi
Name: main_category, Length: 11011, dtype: category
Categories (262, object): ['accesorii-pentru-bucatarie-si-vesela', 'accessoires-de-rangement', 'accessories',
                           'agyak-es-matracok', ..., 'zavesy-a-rolety', 'zavjese-i-zastori',
                           'zimski-praznici', 'zofe-in-foteliji']

In [ ]:
df.isnull().sum()

unique_id                   0
product_id                  0
product_name                0
product_type                0
product_measurements        0
product_description         0
main_category               0
sub_category                0
product_rating           1348
product_rating_count     1348
badge                       0
online_sellable             0
url                         0
price                       1
currency                    1
discount                11011
sale_tag                    1
country                     1
dtype: int64

In [ ]:
df['product_rating'] = df['product_rating'].fillna(df['product_rating'].median())
df['product_rating']

0        3.3
1        3.3
2        1.0
3        3.7
4        3.7
        ...
11006    4.3
11007    2.0
11008    4.3
11009    4.3
11010    4.3
Name: product_rating, Length: 11011, dtype: float64

In [ ]:
df['product_rating_count'] = df['product_rating_count'].fillna(0)
df['product_rating_count']

0        140.0
1          6.0
2          1.0
3        543.0
4        543.0
         ...
11006     78.0
11007      2.0
11008     78.0
11009     78.0
11010     78.0
Name: product_rating_count, Length: 11011, dtype: float64

In [ ]:
df.isnull().sum()

unique_id                   0
product_id                  0
product_name                0
product_type                0
product_measurements        0
product_description         0
main_category               0
sub_category                0
product_rating              0
product_rating_count        0
badge                       0
online_sellable             0
url                         0
price                       1
currency                    1
discount                11011
sale_tag                    1
country                     1
dtype: int64

In [ ]:
df['price'] = df['price'].fillna(df['price'].median())
df['price']

0        30.00
1        27.99
2         9.50
3        29.99
4        34.99
         ...
11006     3.00
11007     1.50
11008     2.00
11009     2.00
11010    64.97
Name: price, Length: 11011, dtype: float64

In [ ]:
df.dtypes

unique_id                 object
product_id                 int64
product_name              object
product_type              object
product_measurements      object
product_description       object
main_category           category
sub_category            category
product_rating           float64
product_rating_count     float64
badge                     object
online_sellable             bool
url                       object
price                    float64
currency                category
discount                 float64
sale_tag                  object
country                 category
dtype: object

In [ ]:
df['discount'] = df['discount'].fillna("0.00")
df['discount']

0        0.00
1        0.00
2        0.00
3        0.00
4        0.00
         ...
11006    0.00
11007    0.00
11008    0.00
11009    0.00
11010    0.00
Name: discount, Length: 11011, dtype: object

In [ ]:
df['discount'].dtype

dtype('O')

In [ ]:
df['discount'] = pd.to_numeric(df['discount'], errors='coerce')
df['discount'].dtype

dtype('float64')

In [ ]:
df.isnull().sum()

unique_id               0
product_id              0
product_name            0
product_type            0
product_measurements    0
product_description     0
main_category           0
sub_category            0
product_rating          0
product_rating_count    0
badge                   0
online_sellable         0
url                     0
price                   0
currency                1
discount                0
sale_tag                1
country                 1
dtype: int64

In [ ]:
df.head(3)

**Categorical Column**

*   sale_tag
*   country
*   currency

In [ ]:
df.dtypes

unique_id                 object
product_id                 int64
product_name              object
product_type              object
product_measurements      object
product_description       object
main_category           category
sub_category            category
product_rating           float64
product_rating_count     float64
badge                     object
online_sellable             bool
url                       object
price                    float64
currency                category
discount                 float64
sale_tag                  object
country                 category
dtype: object

In [ ]:
df.tail()

,unique_id,product_id,product_name,product_type,product_measurements,product_description,main_category,sub_category,product_rating,product_rating_count,badge,online_sellable,url,price,currency,discount,sale_tag,country
11006,10494138-Australia,10494138,RUNNEN,"Corner strip, outdoor floor decking",none,"RUNNEN Corner strip, outdoor floor decking, da...",outdoor-living,outdoor-flooring,4.3,78.0,none,True,https://www.ikea.com/au/en/p/runnen-corner-str...,3.00,AUD,0.0,NONE,Australia
11007,10494138-Austria,10494138,RUNNEN,"Corner strip, outdoor floor decking",none,Black plastic corner and edge strips for decki...,outdoor-living,outdoor-flooring,2.0,2.0,none,True,https://www.ikea.com/at/en/p/runnen-corner-str...,1.50,EUR,0.0,NONE,Austria
11008,10494138-Belgium,10494138,RUNNEN,"Corner strip, outdoor floor decking",none,Black plastic corner and edge strips for decki...,outdoor-products,outdoor-flooring,4.3,78.0,none,True,https://www.ikea.com/be/en/p/runnen-corner-str...,2.00,EUR,0.0,NONE,Belgium
11009,10494138-Canada,10494138,RUNNEN,"Corner edge, outdoor decking",none,"RUNNEN Corner edge, outdoor decking, dark gray",home-improvement,outdoor-flooring,4.3,78.0,none,True,https://www.ikea.com/ca/en/p/runnen-corner-edg...,2.00,CAD,0.0,NONE,Canada
11010,10494138-Croatia,10494138,RUNNEN,"Kutna letvica, vanjske podne obloge",none,"Crne plastične kutne i rubne trake za pod, diz...",vrtni-proizvodi,vanjske-podne-obloge,4.3,78.0,none,True,https://www.ikea.,64.97,NaN,0.0,NaN,NaN

In [ ]:
df['sale_tag']

0        NONE
1        NONE
2        NONE
3        NONE
4        NONE
         ...
11006    NONE
11007    NONE
11008    NONE
11009    NONE
11010     NaN
Name: sale_tag, Length: 11011, dtype: object

In [ ]:
df['sale_tag']=df['sale_tag'].fillna("NONE")
df['sale_tag']

0        NONE
1        NONE
2        NONE
3        NONE
4        NONE
         ...
11006    NONE
11007    NONE
11008    NONE
11009    NONE
11010    NONE
Name: sale_tag, Length: 11011, dtype: object

In [ ]:
df['country'] = df['country'].fillna(df['country'].mode()[0])

In [ ]:
df['currency'] = df.groupby('country',observed=True)['currency'].transform(
    lambda x: x.fillna(x.mode()[0] if not x.mode().empty else 'Unknown')
)

In [ ]:
df.isnull().sum()

unique_id               0
product_id              0
product_name            0
product_type            0
product_measurements    0
product_description     0
main_category           0
sub_category            0
product_rating          0
product_rating_count    0
badge                   0
online_sellable         0
url                     0
price                   0
currency                0
discount                0
sale_tag                0
country                 0
dtype: int64

In [ ]:
df.tail()

,unique_id,product_id,product_name,product_type,product_measurements,product_description,main_category,sub_category,product_rating,product_rating_count,badge,online_sellable,url,price,currency,discount,sale_tag,country
11006,10494138-Australia,10494138,RUNNEN,"Corner strip, outdoor floor decking",none,"RUNNEN Corner strip, outdoor floor decking, da...",outdoor-living,outdoor-flooring,4.3,78.0,none,True,https://www.ikea.com/au/en/p/runnen-corner-str...,3.00,AUD,0.0,NONE,Australia
11007,10494138-Austria,10494138,RUNNEN,"Corner strip, outdoor floor decking",none,Black plastic corner and edge strips for decki...,outdoor-living,outdoor-flooring,2.0,2.0,none,True,https://www.ikea.com/at/en/p/runnen-corner-str...,1.50,EUR,0.0,NONE,Austria
11008,10494138-Belgium,10494138,RUNNEN,"Corner strip, outdoor floor decking",none,Black plastic corner and edge strips for decki...,outdoor-products,outdoor-flooring,4.3,78.0,none,True,https://www.ikea.com/be/en/p/runnen-corner-str...,2.00,EUR,0.0,NONE,Belgium
11009,10494138-Canada,10494138,RUNNEN,"Corner edge, outdoor decking",none,"RUNNEN Corner edge, outdoor decking, dark gray",home-improvement,outdoor-flooring,4.3,78.0,none,True,https://www.ikea.com/ca/en/p/runnen-corner-edg...,2.00,CAD,0.0,NONE,Canada
11010,10494138-Croatia,10494138,RUNNEN,"Kutna letvica, vanjske podne obloge",none,"Crne plastične kutne i rubne trake za pod, diz...",vrtni-proizvodi,vanjske-podne-obloge,4.3,78.0,none,True,https://www.ikea.,64.97,SEK,0.0,NONE,Sweden

In [ ]:
df['currency'].unique()

['AUD', 'EUR', 'BHD', 'CAD', 'CLP', ..., 'CHF', 'THB', 'AED', 'GBP', 'USD']
Length: 34
Categories (34, object): ['AED', 'AUD', 'BHD', 'CAD', ..., 'SEK', 'SGD', 'THB', 'USD']

In [ ]:
conversion_rates = {
    'INR': 1,
    'USD': 83,
    'EUR': 90,
    'GBP': 105,
    'AUD': 55,
    'CAD': 60,
    'SGD': 62,
    'AED': 23,
    'SAR': 22,
    'BHD': 220,
    'SEK': 7.5,
    'CHF': 95,
    'THB': 2.3,
    'CLP': 0.09
}

In [ ]:
df['price_inr'] = df.apply(
    lambda x: x['price'] * conversion_rates.get(x['currency'], 80),  # default fallback
    axis=1
)

In [ ]:
df['price_inr']

0        1650.000
1        2519.100
2        2090.000
3        2699.100
4        2099.400
           ...
11006     165.000
11007     135.000
11008     180.000
11009     120.000
11010     487.275
Name: price_inr, Length: 11011, dtype: float64

In [ ]:
df[['currency', 'price', 'price_inr']].head()

  currency  price  price_inr
0      AUD  30.00     1650.0
1      EUR  27.99     2519.1
2      BHD   9.50     2090.0
3      EUR  29.99     2699.1
4      CAD  34.99     2099.4

In [ ]:
df.isnull().sum()

unique_id               0
product_id              0
product_name            0
product_type            0
product_measurements    0
product_description     0
main_category           0
sub_category            0
product_rating          0
product_rating_count    0
badge                   0
online_sellable         0
url                     0
price                   0
currency                0
discount                0
sale_tag                0
country                 0
price_inr               0
dtype: int64

In [ ]:
df.dtypes

unique_id                 object
product_id                 int64
product_name              object
product_type              object
product_measurements      object
product_description       object
main_category           category
sub_category            category
product_rating           float64
product_rating_count     float64
badge                     object
online_sellable             bool
url                       object
price                    float64
currency                category
discount                 float64
sale_tag                  object
country                 category
price_inr                float64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11011 entries, 0 to 11010
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   unique_id             11011 non-null  object
 1   product_id            11011 non-null  int64
 2   product_name          11011 non-null  object
 3   product_type          11011 non-null  object
 4   product_measurements  11011 non-null  object
 5   product_description   11011 non-null  object
 6   main_category         11011 non-null  category
 7   sub_category          11011 non-null  category
 8   product_rating        11011 non-null  float64
 9   product_rating_count  11011 non-null  float64
 10  badge                 11011 non-null  object
 11  online_sellable       11011 non-null  bool
 12  url                   11011 non-null  object
 13  price                 11011 non-null  float64
 14  currency              11011 non-null  category
 15  discount              11011 non-null  float64
 16  sale_tag              11011 non-null  object
 17  country               11011 non-null  category
 18  price_inr             11011 non-null  float64
dtypes: bool(1), category(4), float64(5), int64(1), object(8)
memory usage: 1.3+ MB

**Cleaned IKEA Datset**

In [ ]:
 df.to_csv('IKEA_cleaned_dataset.csv', index=False)
 df.to_excel('IKEA_cleaned_dataset.xlsx',index=False)

In [ ]:
from google.colab import files

files.download('IKEA_cleaned_dataset.csv')
files.download('IKEA_cleaned_dataset.xlsx')

## Stage 3 – EDA and Visualizations

Univariate Analysis → distribution of single variables (countplot, histogram, boxplot)

Bivariate Analysis → relation between two variables (scatterplot, barplot, correlation heatmap)

Multivariate Analysis → relation among 3+ variables (pairplot, grouped analysis, pivot tables, advanced plots)

Interpretation MUST with every visualization

Focus on business story not just charts

Each chart must be in seperate cells.

In [ ]:
# your chart here
# If you want more cells, you can add or less cells you can remove, but dont change the structure.

## Interpretation of your above chart

Explain the Chart.

What is it saying?

What features you used?

From this what you are showing us?

In [ ]:
# your code here
# If you want more cells, you can add or less cells you can remove, but dont change the structure.

## Interpretation of your above chart

Explain the Chart.

What is it saying?

What features you used?

From this what you are showing us?

In [ ]:
# your code here
# If you want more cells, you can add or less cells you can remove, but dont change the structure.

## Interpretation of your above chart

Explain the Chart.

What is it saying?

What features you used?

From this what you are showing us?

In [ ]:
# your code here
# If you want more cells, you can add or less cells you can remove, but dont change the structure.

## Interpretation of your above chart

Explain the Chart.

What is it saying?

What features you used?

From this what you are showing us?

In [ ]:
# your code here
# If you want more cells, you can add or less cells you can remove, but dont change the structure.

## Interpretation of your above chart

Explain the Chart.

What is it saying?

What features you used?

From this what you are showing us?

## Stage 4 – Documentation, Insights and Presentation

Show a dashboard aligning all the charts in powerbi by connecting python in PowerBI

Summarize findings in plain English (what do the patterns mean)

Highlight 3–5 key insights (trends, anomalies, correlations)

Provide recommendations for business or decision-making

Explain the FINAL STORY WITH THE DASHBOARD

Create a PDF pasting your DASHBOARD, explaining all the above mentioned concepts and submit it

In [ ]:
# your stage 4 pdf Link

'''
step1 --> Create a docs that should have all the above mentioned
step2 --> Save it as "Stage4_doc"
Step3 --> Download it as PDF
step4 --> Upload the pdf in your drive
step5 --> Right click on your pdf in drive
step6 --> click share and change access into anyone with the link (Viewer)
step7 --> click copy link and paste it here...
You are done.
'''